src/Entity/MatchList.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MatchListRepository")
 */
class MatchList
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(name = "is_starting", type="boolean", nullable=true)
     */
    public $is_starting;
    /**
     * @ORM\Column(name = "is_played", type="boolean", nullable=true)
     */
    public $is_played;
    /**
     * @ORM\Column(name = "goals", type="integer", nullable=true)
     */
    public $goals;
    /**
     * @ORM\Column(name = "assits", type="integer", nullable=true)
     */
    public $assits;
    /**
     * @ORM\Column(name = "saves", type="integer", nullable=true)
     */
    public $saves;
    /**
     * @ORM\Column(name = "played_time", type="integer", nullable=true)
     */
    public $playedTime;
    /**
     * @ORM\Column(name = "start_time", type="integer", nullable=true)
     */
    public $startTime;

    /**
     * @ORM\Column(name = "end_time", type="integer", nullable=true)
     */
    public $endTime;

    /**
     * @ORM\ManyToOne(targetEntity="Matches", inversedBy="matchList")
     * @ORM\JoinColumn(name="matches", referencedColumnName="id")
     */
    public $match;

    /**
     * @ORM\ManyToOne(targetEntity="Player", inversedBy="matchList")
     * @ORM\JoinColumn(name="player", referencedColumnName="id")
     */
    public $player;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getIsStarting()
    {
        return $this->is_starting;
    }

    /**
     * @param mixed $is_starting
     */
    public function setIsStarting($is_starting): void
    {
        $this->is_starting = $is_starting;
    }

    /**
     * @return mixed
     */
    public function getIsPlayed()
    {
        return $this->is_played;
    }

    /**
     * @param mixed $is_played
     */
    public function setIsPlayed($is_played): void
    {
        $this->is_played = $is_played;
    }

    /**
     * @return mixed
     */
    public function getGoals()
    {
        return $this->goals;
    }

    /**
     * @param mixed $goals
     */
    public function setGoals($goals): void
    {
        $this->goals = $goals;
    }

    /**
     * @return mixed
     */
    public function getAssits()
    {
        return $this->assits;
    }

    /**
     * @param mixed $assits
     */
    public function setAssits($assits): void
    {
        $this->assits = $assits;
    }

    /**
     * @return mixed
     */
    public function getSaves()
    {
        return $this->saves;
    }

    /**
     * @param mixed $saves
     */
    public function setSaves($saves): void
    {
        $this->saves = $saves;
    }

    /**
     * @return mixed
     */
    public function getPlayedTime()
    {
        return $this->playedTime;
    }

    /**
     * @param mixed $playedTime
     */
    public function setPlayedTime($playedTime): void
    {
        $this->playedTime = $playedTime;
    }

    /**
     * @return mixed
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     * @param mixed $startTime
     */
    public function setStartTime($startTime): void
    {
        $this->startTime = $startTime;
    }

    /**
     * @return mixed
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     * @param mixed $endTime
     */
    public function setEndTime($endTime): void
    {
        $this->endTime = $endTime;
    }

    /**
     * @return mixed
     */
    public function getMatch()
    {
        return $this->match;
    }

    /**
     * @param mixed $match
     */
    public function setMatch($match): void
    {
        $this->match = $match;
    }

    /**
     * @return mixed
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * @param mixed $player
     */
    public function setPlayer($player): void
    {
        $this->player = $player;
    }






}

src/Entity/Requests/Coach/CoachToTeamRequest.php
<?php

namespace App\Entity\Requests\Coach;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Requests\Coach\CoachToTeamRequestRepository")
 */
class CoachToTeamRequest
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Coach", inversedBy="requestsToTeams")
     * @ORM\JoinColumn(name="coaches", referencedColumnName="id")
     */

    public $coach;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Team", inversedBy="requestFromCoach")
     * @ORM\JoinColumn(name="teams", referencedColumnName="id")
     */
    public $team;


    /**
     * @var date
     *
     * @ORM\Column(name="dates", type="string", nullable=false)
     */
    public $date;



    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getCoach()
    {
        return $this->coach;
    }

    /**
     * @param mixed $coach
     */
    public function setCoach($coach): void
    {
        $this->coach = $coach;
    }

    /**
     * @return mixed
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * @param mixed $team
     */
    public function setTeam($team): void
    {
        $this->team = $team;
    }

    /**
     * @return date
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param date $date
     */
    public function setDate($date): void
    {
        $this->date = $date;
    }



}

src/Form/CoachType.php
<?php

namespace App\Form;

use App\Entity\Coach;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CoachType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('birthDay')
            ->add('image')
            ->add('status')
            ->add('youthTeam')
            ->add('team')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Coach::class,
        ]);
    }
}

src/Form/MatchesType.php
<?php

namespace App\Form;

use App\Entity\Matches;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MatchesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('homeTeam')
            ->add('awayTeam')
            ->add('date')
            ->add('time')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Matches::class,
        ]);
    }
}

src/Controller/Coach/CoachController.php
<?php

namespace App\Controller\Coach;


use App\Service\CoachService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;




class CoachController extends AbstractController
{
    const PrefixRoutePath = "coach";
    const HeadCoach = 'HEAD_COACH';
    const requestType = "coach-player";
    protected $coachService;
    private $bCryptAlgorithmOption;
    public function __construct(CoachService $coachService)
    {
        $this->coachService = $coachService;
        $this->bCryptAlgorithmOption = [
            'cost' => 12,
        ];
    }





    private function binarySearch($l, $r, $x)
    {
        $arr[] = range(0, 1000000);
        while ($l <= $r)
        {
            $m = $l + ($r - $l) / 2;

            // Check if x is present at mid
            if (password_verify($x, $arr[$m] ))
                return floor($m);

            // If x greater, ignore
            // left half
            if ($arr[$m] < $x)
                $l = $m + 1;

            // If x is smaller,
            // ignore right half
            else
                $r = $m - 1;
        }

        // if we reach here, then
        // element was not present
        return -1;
    }

}

src/Controller/Coach/CoachGetController.php
<?php

namespace App\Controller\Coach;

use App\Entity\Coach;
use App\Entity\Matches;
use App\Entity\Player;
use App\Entity\Schedule;
use App\Entity\Shoes\ShoesType;
use App\Entity\Training;
use App\Entity\TrainingPieces\TrainingType;
use App\Entity\User;
use App\Form\PlayerType;
use App\Form\ScheduleType;
use App\Form\UserType;
use App\Repository\MatchesRepository;
use App\Repository\PlayerRepository;
use App\Repository\Shoes\ShoesTypeRepository;
use App\Repository\TeamRepository;
use App\Repository\TrainingPieces\TrainingTypeRepository;
use App\Repository\TrainingRepository;
use App\Service\CoachService;
use App\Service\FileService;
use App\Service\PlayerService;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CoachGetController extends CoachController
{

    /**
     * @Route("/coache", name = "coacheViewAction" )
     */
    public function CoacheViewAction(TeamRepository $teamRepository, PlayerRepository $playerRepository){
        $coach = $this->getUser()->getCoaches();

        $teamCoach = $this->coachService->getCoachTeam($coach);
        $topPlayers = $this->coachService->getTopPlayersFromCoachTeam($playerRepository, $coach);
        if ($teamCoach == null){
            $players = 0;
            $teams = null;
            $hasTeam = false;
        }else {
            $hasTeam = true;
            $teams = $teamRepository->getTeamByDivisionDesc($teamCoach->getDivision()->getId());
            $players = $teamCoach->getPlayers();
        }
        $teamPosition = 0;
        for ($i = 0; $i < count($teams); $i++){
            if ($teams[$i]->getId() == $teamCoach->getId()){
                $teamPosition = $i + 1;
            }
        }

        return $this->render('coaches/index.html.twig', array(
            'playersCount' => count($players),
            'cups' => 0,
            'players' => $players,
            'topPlayers' => $topPlayers,
            'name' => $this->getUser()->getName() ,
            'fName' => $this->getUser()->getFName(),
            'profile_img' => $this->getUser()->getCoaches()->getImage(),
            'division' => $teamCoach->getDivision()->getName(),
            'hasTeam' => $hasTeam,
            'myTeam' => $teamCoach,
            'teams' =>$teams,
            'teamPosition' =>$teamPosition,

        ));

    }

    /**
     * @Route("/coache/trainings", name = "trainingView", methods = {"GET"})
     */
    public function TrainingView(Request $request)
    {
        $user = new User();
        $player = new Player();
        $coach = $this->getUser()->getCoaches();
        $teamCoach = $this->coachService->getCoachTeam($coach);

        if ($teamCoach == null){
            $players = null;
        }else{
            $players = $teamCoach->getPlayers();
        }

        $form_user = $this->createForm(UserType::class, $user);
        $form_player = $this->createForm(PlayerType::class, $player)->add('position');

        $form_player->handleRequest($request);
        $form_user->handleRequest($request);

        if($form_player->isSubmitted() && $form_user->isSubmitted()){
            $playerPhone = $player->getPhone();
            $validPhoneNum = $this->getDoctrine()->getRepository(Players::class)->findBy(array('phone' => $playerPhone));
            if (count($validPhoneNum) > 0){
                return "This phone number is already in database";
            }else {
                $positionId =   json_decode($request->request->get('position'));
                $position = $this->getDoctrine()->getRepository(Positions::class)->find((int)$positionId);
                $player->setPosition($position);
                $player->setTeam($teamCoach);

                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();

                $player->setUser($user);
                $em->persist($player);
                $em->flush();
                return "All data is inserted";
            }
        }

        $user = $this->getUser()->getCoaches();
        return $this->render('coaches/trainings/training.html.twig',array(
            'profile_img' => $user->getImage(),
            'coachTeamName' => $teamCoach->getName(),
            'coachTeamImage' => $teamCoach->getImage(),
            'coachPosition' => $coach->getTeamPosition()->getName(),
            'players' => $players
        ));
    }



    /**
     * @Route("/coache/trainingCalendar", defaults={"reactRouting" }, name = "trainingCalendarActionView")
     */
    public function TrainingCalendarViewAction(ShoesTypeRepository $shoesTypeRepository, TrainingTypeRepository $trainingTypeRepository, Request $request, TrainingRepository $trainingRepository, MatchesRepository $matchesRepository )
    {
        $em = $this->getDoctrine()->getManager();
        $coach = $this->getUser()->getCoaches();

        $schedule = new Schedule();
        $form = $this->createForm(ScheduleType::class, $schedule);
        $form->add('training', \App\Form\TrainingType::class);
        $form->handleRequest($request);

        $schedules  = [];
        $schedules2 = $this->getDoctrine()->getRepository(Schedule::class)->findBy(['coaches' => $coach->getId()]);

        $Current = strval(Date('d/m/Y'));
        $currentMonth = explode('/', $Current);

        for ( $i = 0; $i < count($schedules2); $i++ ){
            $dates = explode('/', strval($schedules2[$i]->getDate()));
            if ($currentMonth[1] == $dates[1] && $dates[0] == $currentMonth[0]){
                array_push($schedules, $schedules2[$i]);
            }
        }

        if ($form->isSubmitted()) {
            $schedule->setCoaches($coach);
            $em = $this->getDoctrine()->getManager();
            $em->persist($schedule);
            $em->flush();
            exit;
        }

        return $this->render('coaches/trainings/trainingCalendar.html.twig',
            array("form" => $form->createView(),
                'profile_img' => $coach->getImage(),
                'schedules' => $schedules,
                'shoesTypes' => $shoesTypeRepository->findAll(),
                'trainingTypes' => $trainingTypeRepository->findAll()

            ));

    }

    /**
     * @Route("/coache/settings", name = "coache_settings")
     *
     */
    public function SettingsView(\Symfony\Component\HttpFoundation\Request $request, FileService $fileService){
        $coach = $this->getUser()->getCoaches();
        $newCoach = new Coach();
        $form = $this->createFormBuilder($newCoach)
            ->add('image', FileType::class, array('data_class' => null, ))
            ->add('save', SubmitType::class, ['label' => 'Задай новата снимка'])
            ->getForm();
        $form->handleRequest($request);

        $coachNewFileName = $fileService->MoveImage($form);
        if ($coachNewFileName != null) {
            $em = $this->getDoctrine()->getManager();
            $coach->setImage($coachNewFileName);
            $em->persist($coach);
            $em->flush();

        }

        return $this->render('coaches/settings/settings.html.twig',
            array(
                'form' => $form->createView(),
                "image" =>  $coach->getImage(),
                "coach" => $coach,
                "profile_img" => $coach->getImage()

            ));
    }

    /**
     * @Route("/coache/player/{id}", name = "playerStatsView")
     *
     */
    public function PlayerAction($id, \Symfony\Component\HttpFoundation\Request $request, PlayerService $playerService, CoachService $coachService)
    {
        $coach = $this->getUser()->getCoaches();
        $player = $this->getDoctrine()->getRepository(Player::class)->find($id);
        $playerStats = $player->getStats();
        $newPlayers = new Player();

        $form = $this->createFormBuilder($newPlayers)->add('pace');

        $playerTeam = $playerService->getPlayerTeam($player);
        $coachTeam = $coachService->getCoachTeam($coach);

        if ($playerTeam->getId() != $coachTeam->getId() &&
            (
                ($player->getYouthTeam() == null && $coach->getYouthTeam() != null) ||
                ($player->getYouthTeam() != null && $coach->getYouthTeam() == null)
            )
        ){
            return $this->redirectToRoute("trainingView");
        }

        $playedMatches = $playerService->getPlayedMatches($player);
        $titularMatchers = $playerService->getTitularPlayedMatches($player);
        $playerGoals = $playerService->getGoals($player);
        $playedMinutes = $playerService->getTotalPlayedMinutes($player);
        return $this->render('coaches/playerStat.html.twig',
            array(
                'profile_img' => $coach->getImage(),
                'player' => $player,
                'playerStats' => $playerStats,
                'image' => $player->getImage(),
                'playedMatches' => $playedMatches,
                'titularMatches' => $titularMatchers,
                'goals' => $playerGoals,
                'playedMinutes' => $playedMinutes
            )
        );
    }

    /**
     * @Route("/coache/searchEngine", name = "searchEngine")
     */
    public function SearchEngine(\Symfony\Component\HttpFoundation\Request $request)
    {
        return $this->render("coaches\searchEngine.html.twig", array('profile_img' => null));
    }

}

templates/coaches/matches/match.html.twig
{% extends 'coaches/base.html.twig' %}
{% block style %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/particles/matchCard.css') }}">
    <link rel="stylesheet" href="{{ asset('css/particles/fut-player-card.css') }}">
{% endblock %}
{% block navLinks %}
    <a class="ml-2 na navbar-link " href="{{ path("trainingView") }}">Начална страница</a>
    <a class="ml-2 na navbar-link " href="{{ path("trainingView") }}">Отбор</a>
    <a class="ml-2 na navbar-link " href="{{ path("trainingCalendarActionView") }}">Тренировъчен план</a>
    <a class="ml-2 na navbar-link current-item" href="{{ path("coachMatches") }}">Мачове</a>
    <a class="ml-2 na navbar-link" href="{{ path("allRequestsView") }}">Заявки</a>
{% endblock %}
{% block body %}
    <div class="col-12 col-lg-12 p-0 mt-4 row justify-content-center mx-auto max-resolution">
        <div class="col-lg-11 col-md-7 p-0 col-sm-11 col-10 justify-content-around  row pb-3">
            <div class="col-12 mt-2 mb-3">
                <h2 class="col-12 mb-3 text-center"><b>Моля иберете играчи за групата за мача </b></h2>
                <h3 class="col-12 text-center">Брой играчи на {{team }}: {{players|length}}</h3>
                <h3 class="col-12 text-center">Максимален брой играчи в групата: 18</h3>
            </div>
            {% for player in players %}
                <div class="wrapper col-lg-3 col-md-6 col-sm-6">
                    <!-- *** fut-player-card ***-->
                    <div class="fut-player-card" id="{{ player.id }}-{{ player.position.Name }}">
                        <!-- Player Card Top-->
                        <div class="player-card-top">
                            <div class="player-master-info">
                                <div class="player-rating"><span >{{ player.stats.statusFromCoaches }}</span></div>
                                <div class="player-position"><span class="position">{{ player.position.Name }}</span></div>
                                <div class="player-nation"><img src="{{ asset('images/' ~ player.User.City.Country.Image) }}" alt="Argentina" draggable="false" /></div>
{#                                <div class="player-club"><img src="{{ asset('images/' ~ player.Team.Image) }}" alt="Barcelona" draggable="false" /></div>#}
                            </div>
                            <div class="player-picture"><img src="{{ asset('images/' ~ player.Image) }}" alt="Messi" draggable="false" />

                            </div>
                        </div>
                        <!-- Player Card Bottom-->
                        <div class="player-card-bottom">
                            <div class="player-info">
                                <!-- Player Name-->
                                <div class="player-name"><span>{{ player.user.fName }}</span></div>
                                <!-- Player Features-->
                                <div class="player-features">
                                    <div class="player-features-col"><span>
                                            <div class="player-feature-value">97</div><div class="player-feature-title">PAC</div></span><span><div class="player-feature-value">95</div><div class="player-feature-title">SHO</div></span><span><div class="player-feature-value">94</div><div class="player-feature-title">PAS</div></span></div>
                                    <div class="player-features-col"><span><div class="player-feature-value">99</div><div class="player-feature-title">DRI</div></span><span><div class="player-feature-value">35</div><div class="player-feature-title">DEF</div></span><span><div class="player-feature-value">68</div><div class="player-feature-title">PHY</div></span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <button class="sendPlayers btn btn-success  p-4">Потвърдете изборът си!</button>
        </div>
    </div>
    <script src="{{ asset("js/coach/matchGroupListEvent.js") }}"></script>
{% endblock %}

templates/coaches/matches/pastMatches.html.twig
{% extends 'coaches/base.html.twig' %}
{% block style %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/particles/matchCard.css') }}">
    <link rel="stylesheet" href="{{ asset('css/particles/fut-player-card.css') }}">
      <link rel="stylesheet" href="  {{ asset("css/superAdmin/matchPageStyle.css") }}">
      <link rel="stylesheet" href="  {{ asset("css/particles/tableViewStyle.css") }}">
{% endblock %}
{% block navLinks %}
    <a class="ml-2 na navbar-link " href="{{ path("trainingView") }}">Начална страница</a>
    <a class="ml-2 na navbar-link " href="{{ path("trainingView") }}">Отбор</a>
    <a class="ml-2 na navbar-link " href="{{ path("trainingCalendarActionView") }}">Тренировъчен план</a>
    <a class="ml-2 na navbar-link current-item" href="{{ path("coachMatches") }}">Мачове</a>
    <a class="ml-2 na navbar-link" href="{{ path("allRequestsView") }}">Заявки</a>
{% endblock %}
{% block body %}
    <div class="col-12 col-lg-12 p-0 mt-4 row justify-content-center mx-auto max-resolution">
        <div class="col-lg-11 col-md-7 p-0 col-sm-11 col-10 justify-content-center  row pb-3">
          <div class="container col-12 p-0 m-0">
            <div class="col-12 match-date-time justify-content-center text-center mt-2 mb-1">
                <h5 class="information">Дата на мача: {{ match.date }} {{ match.time }}</h5>
            </div>
          </div>
          <div class="container m-0 p-0    col-12 row">
              <div class="col-12 row p-0 m-0 justify-content-center">
                  <div class="match-info-holder col-11 row mt-3  mx-auto  justify-content-center p-0">
                      <div class="homeTeam-info-holder col-5 p-0 m-0 text-center justify-content-center ">
                          <img src="{{ asset("images/" ~ match.homeTeam.Image) }}" class="mx-auto" alt="">
                          <h3>{{ match.homeTeam.Name }}</h3>
                          <h2>{{ match.MatchStats.HomeTeamGoals }}</h2>

                      </div>
                      <div class="col-1  m-0 p-0 row mx-auto">
                        <h3 class="mx-auto col-12 my-auto">-</h3>
                      </div>
                      <div class="awayTeam-info-holder col-5 p-0 m-0 text-center">
                          <img src="{{ asset("images/" ~ match.awayTeam.Image) }}" class="mx-auto" alt="">
                          <h3>{{ match.awayTeam.Name }}</h3>
                          <h2>{{ match.MatchStats.AwayTeamGoals }}</h2>
                      </div>
                  </div>
              </div>
          </div>
        </div>
    </div>


    <div class="col-12 container">
        <table class=" col-12 mt-5"  style="margin-bottom: 0; padding:0;">
            <thead>
            <tr class="row col-12 p-1 m-0 table-color">
                {% if match.HomeTeam.Id == coach.Team.Id %}
                    <th class="col-2 col-lg-4 color-white"><img src="{{ asset("images/"~match.HomeTeam.Image) }}" alt="">{{match.HomeTeam.Name}}</th>
                    {% else %}
                        <th class="col-2 col-lg-4 color-white"><img src="{{ asset("images/"~match.AwayTeam.Image) }}" alt="">{{match.AwayTeam.Name}}</th>
                {% endif %}
                <th class="col-1 my-auto color-white">Г</th>
                <th class="col-1 my-auto color-white">А</th>
                <th class="col-1 my-auto color-white">У</th>
                <th class="col-2 col-lg-1 my-auto color-white">Започнали</th>
                <th class="col-1 my-auto color-white">От</th>
                <th class="col-1 my-auto color-white">До</th>
                <th class="col-1 my-auto color-white">Позиция</th>
            </tr>
            </thead>
            <tr class="startedPlayers">
                <th class="col-12 text-center p-1"><h4>Титуляри</h4></th>
            </tr>
            {% for matchList in match.MatchList %}
                {% if matchList.Player.Team.Id == coach.Team.Id %}
                    {% if matchList.IsStarting == 1 %}
                        {% set player = matchList.Player %}
                        <tr class="teamTable homeTeamPlayer row col-12 p-1 m-0">
                            <th  class="col-2 col-lg-4 justify-content-end"><img src="{{ asset("images/"~player.Image) }}" alt=""> {{ player.User.Name }} {{  player.User.FName}} </th>
                            <th class="col-1 my-auto">{{ matchList.goals }}</th>
                            <th class="col-1 my-auto">{{ matchList.assits }}</th>
                            <th class="col-1 my-auto">{{ matchList.saves }}</th>
                            {% if matchList.isPlayed == 1 %}
                                <th class="col-2 col-lg-1 my-auto">Да</th>
                                {% else %}
                                <th class="col-2 col-lg-1 my-auto">Не</th>

                            {% endif %}
                            <th class="col-1 my-auto">{{ matchList.startTime }}</th>
                            <th class="col-1 my-auto">{{ matchList.endTime }}</th>
                            <th class="col-1 my-auto"><p>{{player.Position}}</p></th>
                            <input type="hidden" name="" value="{{matchList.IsStarting}}">
                            <input type="hidden" name="" value="{{player.Id}}">


                        </tr>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <tr class="reservePlayers">
                <th class="col-12 text-center p-1"><h4>Резерви</h4></th>
            </tr>
            {% for matchList in match.MatchList %}
                {% if matchList.Player.Team.Id == coach.Team.Id %}
                    {% if matchList.IsStarting == 1 %}
                        {% set player = matchList.Player %}
                        <tr class="teamTable homeTeamPlayer row col-12 p-1 m-0">
                            <th  class="col-2 col-lg-4 justify-content-end"><img src="{{ asset("images/"~player.Image) }}" alt=""> {{ player.User.Name }} {{  player.User.FName}} </th>
                            <th class="col-1 my-auto">{{ matchList.goals }}</th>
                            <th class="col-1 my-auto">{{ matchList.assits }}</th>
                            <th class="col-1 my-auto">{{ matchList.saves }}</th>
                            {% if matchList.isPlayed == 1 %}
                                <th class="col-2 col-lg-1 my-auto">Да</th>
                            {% else %}
                                <th class="col-2 col-lg-1 my-auto">Не</th>

                            {% endif %}
                            <th class="col-1 my-auto">{{ matchList.startTime }}</th>
                            <th class="col-1 my-auto">{{ matchList.endTime }}</th>
                            <th class="col-1 my-auto"><p>{{player.Position}}</p></th>
                            <input type="hidden" name="" value="{{matchList.IsStarting}}">
                            <input type="hidden" name="" value="{{player.Id}}">


                        </tr>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </table>
      
    </div>
{% endblock %}